---
- name: "catalogue installation"
  hosts: catalogue
  become: yes
  tasks:
  - name: "disable and enable nodejs"
    ansible.builtin.command: dnf module disable nodejs -y ; dnf module enable nodejs:18 -y
  - name: "install nodejs"
    ansible.builtin.package:
     name: "nodejs"
     state: present   