---
- name: configuring web module
  hosts: web
  become: yes
  tasks:
  
- name: Install nginx package
  ansible.builtin.dnf:
   name: nginx
   state: present

- name: Start and enable nginx
  ansible.builtin.service:
   name: nginx
   state: started
   enabled: yes
   